// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyOp-x6dQxJjRKCAZgaTtwo6lv7i7JCg',
    appId: '1:78101399654:android:eb7f63cce290e9e79705a7',
    messagingSenderId: '78101399654',
    projectId: 'malvinas-9d9e7',
    storageBucket: 'malvinas-9d9e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzyCciY5EHWWsM_tNPACCZ-lspViHffX8',
    appId: '1:78101399654:ios:f7e92f1f601321079705a7',
    messagingSenderId: '78101399654',
    projectId: 'malvinas-9d9e7',
    storageBucket: 'malvinas-9d9e7.appspot.com',
    iosClientId: '78101399654-ne5emcop4rptj3llqpp8v0h5dja922gr.apps.googleusercontent.com',
    iosBundleId: 'com.malvinas',
  );
}
