// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDltJfRJ_qmoezA09XCGIN3tgmcVTYuYTo',
    appId: '1:78101399654:web:aeb4e8afded5d9b69705a7',
    messagingSenderId: '78101399654',
    projectId: 'malvinas-9d9e7',
    authDomain: 'malvinas-9d9e7.firebaseapp.com',
    storageBucket: 'malvinas-9d9e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyOp-x6dQxJjRKCAZgaTtwo6lv7i7JCg',
    appId: '1:78101399654:android:eb7f63cce290e9e79705a7',
    messagingSenderId: '78101399654',
    projectId: 'malvinas-9d9e7',
    storageBucket: 'malvinas-9d9e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzyCciY5EHWWsM_tNPACCZ-lspViHffX8',
    appId: '1:78101399654:ios:522e7c3d4c2c5d339705a7',
    messagingSenderId: '78101399654',
    projectId: 'malvinas-9d9e7',
    storageBucket: 'malvinas-9d9e7.appspot.com',
    iosClientId: '78101399654-ha4vo7dhafahctaei6p7gdqoe7h61885.apps.googleusercontent.com',
    iosBundleId: 'com.example.Malvinas',
  );
}
